Including a newer version of gcccpuopt from http://www.pixelbeat.org/scripts/gcccpuopt as on a Digital Ocean (and likely other) VM the compilation has an unknown CPU warning.

diff --git a/build/gcccpuopt b/build/gcccpuopt
--- a/build/gcccpuopt
+++ b/build/gcccpuopt
@@ -57,11 +57,11 @@
 #   V0.99.3, 11 Aug 2009, Support for AMD Geode LX processor.
 #   V0.99.4, 24 Oct 2009, Following a report from Maxime de Roucy, add support
 #                         for AMD family 17 (griffin).
-#   V0.99.10, 22 Aug 2012
+#   V0.99.11, 04 Jul 2013
 #     http://github.com/pixelb/scripts/commits/master/scripts/gcccpuopt
 
 if [ "$1" = "--version" ]; then
-    echo "0.99.10" && exit
+    echo "0.99.11" && exit
 fi
 
 # This table shows when -march options were introduced into _official_ gcc releases.
@@ -90,17 +90,17 @@ if ! try_gcc_options; then
     exit 1
 fi
 
-#if try_gcc_options -march=native; then
-#    echo "Warning: Your compiler supports the -march=native option which you may prefer" >&2
-#    gcc -march=native --verbose -xc /dev/null 2>&1 | sed -n 's|.*/dev/null \(-march.*-mtune[^ ]*\).*|\1|p' >&2
-#fi
+if try_gcc_options -march=native; then
+    echo "Warning: Your compiler supports the -march=native option which you may prefer" >&2
+    #gcc -march=native --verbose -xc /dev/null 2>&1 | sed -n 's|.*/dev/null \(-march.*-mtune[^ ]*\).*|\1|p' >&2
+fi
 
 if ! try_gcc_options -march=i386; then
     if ! try_gcc_options -m32 -march=i386; then
-        #echo "Error: This script only supports 32 bit x86 architectures" >&2
+        echo "Error: This script only supports 32 bit x86 architectures" >&2
         exit 1
     else
-        #echo "Warning: The optimum *32 bit* architecture is reported" >&2
+        echo "Warning: The optimum *32 bit* architecture is reported" >&2
         m32="-m32 "
     fi
 fi
@@ -113,7 +113,7 @@ try_line() {
             return
         elif [ "$skip" = "0" ] && [ "$arch" != "native" ]; then
             skip=1
-            #echo "Warning: Newer versions of GCC better support your CPU with -march=$arch" >&2
+            echo "Warning: Newer versions of GCC better support your CPU with -march=$arch" >&2
         fi
     done
     return 1
@@ -274,8 +274,13 @@ elif [ "$vendor_id" = "GenuineIntel" ]; then
     elif [ $cpu_family -eq 6 ]; then
         if [ \( $cpu_model -eq 0 \) -o \( $cpu_model -eq 1 \) ]; then
             _CFLAGS="-march=pentiumpro"
-        elif [ \( $cpu_model -ge 3 \) -a \( $cpu_model -le 6 \) ]; then #4=TM5600 at least
+        elif [ \( $cpu_model -ge 2 \) -a \( $cpu_model -le 6 \) ]; then #4=TM5600 at least
             line="pentium2 pentiumpro pentium-mmx pentium i486 i386"
+            if [ \( $cpu_model -eq 2 \) ]; then #qemu generic
+                echo "\
+Warning: Unspecified QEMU CPU model.
+Please consider upgrading QEMU or configuring it to use a specific model." >&2
+            fi
         elif [ \( $cpu_model -eq 9 \) -o \( $cpu_model -eq 13 \) ]; then #centrino
             line="pentium-m pentium4 pentium3 pentium2 pentiumpro pentium-mmx pentium i486 i386"
         elif [ \( $cpu_model -eq 14 \) ]; then #Core
@@ -356,11 +361,11 @@ fi
 
 #SSE is not used for floating point by default in gcc 32 bit
 #so turn that on here.
-#if echo "$flags" | grep -q "sse"; then
-#    if try_gcc_options "-mfpmath=sse"; then #gcc >= 3.1
-#        _CFLAGS="$_CFLAGS -mfpmath=sse"
-#    fi
-#fi
+if echo "$flags" | grep -q "sse"; then
+    if try_gcc_options "-mfpmath=sse"; then #gcc >= 3.1
+        _CFLAGS="$_CFLAGS -mfpmath=sse"
+    fi
+fi
 
 #The SSE options are mostly selected automatically
 #when a particular march option is selected.
@@ -370,28 +375,28 @@ fi
 #   amd:   [sse5] sse4a [sse3] sse2 sse ...
 # The bracketed ones are only available on some cpus
 # in a particular family and so need to be added explicitly.
-#if echo "$_CFLAGS" | grep -q "amdfam10"; then
-#    if echo "$flags" | grep -q "sse5"; then
-#        if try_gcc_options "-msse5"; then #gcc >= 4.3
-#            _CFLAGS="$_CFLAGS -msse5"
-#        fi
-#    fi
-#elif echo "$_CFLAGS" | grep -E -q "(k8|c3-2)"; then
-#    if echo "$flags" | grep -E -q "(sse3|pni)"; then
-#        if try_gcc_options "-msse3"; then #gcc >= 3.3.3
-#            _CFLAGS="$_CFLAGS -msse3"
-#        fi
-#    fi
-#elif echo "$_CFLAGS" | grep -q "core2"; then
-#    if echo "$flags" | grep -q "sse4_2"; then
-#        if try_gcc_options "-msse4"; then #gcc >= 4.3
-#            _CFLAGS="$_CFLAGS -msse4"
-#        fi
-#    elif echo "$flags" | grep -q "sse4_1"; then
-#        if try_gcc_options "-msse4.1"; then #gcc >= 4.3
-#            _CFLAGS="$_CFLAGS -msse4.1"
-#        fi
-#    fi
-#fi
+if echo "$_CFLAGS" | grep -q "amdfam10"; then
+    if echo "$flags" | grep -q "sse5"; then
+        if try_gcc_options "-msse5"; then #gcc >= 4.3
+            _CFLAGS="$_CFLAGS -msse5"
+        fi
+    fi
+elif echo "$_CFLAGS" | grep -E -q "(k8|c3-2)"; then
+    if echo "$flags" | grep -E -q "(sse3|pni)"; then
+        if try_gcc_options "-msse3"; then #gcc >= 3.3.3
+            _CFLAGS="$_CFLAGS -msse3"
+        fi
+    fi
+elif echo "$_CFLAGS" | grep -q "core2"; then
+    if echo "$flags" | grep -q "sse4_2"; then
+        if try_gcc_options "-msse4"; then #gcc >= 4.3
+            _CFLAGS="$_CFLAGS -msse4"
+        fi
+    elif echo "$flags" | grep -q "sse4_1"; then
+        if try_gcc_options "-msse4.1"; then #gcc >= 4.3
+            _CFLAGS="$_CFLAGS -msse4.1"
+        fi
+    fi
+fi
 
-echo "$_CFLAGS"
+echo "$m32$_CFLAGS"
