Moving generated code to php5 directory [ci skip]

diff --git a/build/use-pgo-install b/build/use-pgo-install
--- a/build/use-pgo-install
+++ b/build/use-pgo-install
@@ -2,7 +2,7 @@
 
 #  Phalcon Framework
 #
-#  Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)
+#  Copyright (c) 2011-2016 Phalcon Team (http://phalconphp.com)
 #
 #  This source file is subject to the New BSD License that is bundled
 #  with this package in the file docs/LICENSE.txt.
@@ -20,20 +20,23 @@ export GCC_INSTRUMENT_PROGRAM_FLOW_ARCS="YES"
 export CC="gcc"
 export CFLAGS="-march=native -mtune=native -O2 -fno-delete-null-pointer-checks -finline-functions -fno-builtin-memcmp -fprofile-use"
 export CPPFLAGS="-DPHALCON_RELEASE"
+
 echo "int main() {}" > t.c
 gcc $CFLAGS t.c -o t 2> t.t
 if [ $? != 0 ]; then
-        chmod +x gcccpuopt
-        BFLAGS=`./gcccpuopt`
-        export CFLAGS="-O2 -fno-delete-null-pointer-checks -finline-functions $BFLAGS -fno-builtin-memcmp -fprofile-use"
-        gcc $CFLAGS t.c -o t 2> t.t
-        if [ $? != 0 ]; then
-                export CFLAGS="-O2 -fno-delete-null-pointer-checks"
-        fi
+    chmod +x gcccpuopt
+    BFLAGS=`./gcccpuopt`
+    export CFLAGS="-O2 -fno-delete-null-pointer-checks -finline-functions $BFLAGS -fno-builtin-memcmp -fprofile-use"
+    gcc $CFLAGS t.c -o t 2> t.t
+    if [ $? != 0 ]; then
+        export CFLAGS="-O2 -fno-delete-null-pointer-checks"
+    fi
 fi
+
 if [ $(gcc -dumpversion | cut -f1 -d.) -ge 4 ]; then
 	gcc $CFLAGS -fvisibility=hidden t.c -o t 2> t.t && export CFLAGS="$CFLAGS -fvisibility=hidden"
 fi
+
 #gcc $CFLAGS -flto t.c -o t 2> t.t && { export CFLAGS="$CFLAGS -flto"; export LDFLAGS="$LDFLAGS $CFLAGS"; }
 rm -f t.t t.c t
 
@@ -52,13 +55,16 @@ else
 fi
 
 if [ -f $DIR/.libs/phalcon.gcda ]; then
-        cp $DIR/.libs/phalcon.gcda .
+    cp $DIR/.libs/phalcon.gcda .
 else
-        echo "Profile info was not found"
+    echo "Profile info was not found"
 fi
 
-#Move to specified architecture
-cd $DIR
+# Version
+PHP_VERSION="php5"
+
+# Move to specified architecture
+cd "$PHP_VERSION/$DIR"
 
 #export CFLAGS="-O0 -g -fno-delete-null-pointer-checks"
 
@@ -72,10 +78,10 @@ fi
 phpize && ./configure --enable-phalcon
 
 if [ -f ../phalcon.gcda ]; then
-        mkdir .libs
-        cp ../phalcon.gcda .libs/phalcon.gcda
+    mkdir .libs
+    cp ../phalcon.gcda .libs/phalcon.gcda
 else
-        echo "Profile info was not found"
+    echo "Profile info was not found"
 fi
 
 make && make install && echo -e "\nThanks for compiling Phalcon!\nBuild succeed: Please restart your web server to complete the installation"
